### ISSUE TITLE
Big Image Switch stuck

### ISSUE THREAD

**Issue by 4lt3r3go** [alt-key-project/comfyui-dream-project#14]
Among all the image switchers, I use this one because I love it. thank you.

 However, there’s a major issue: 
 when no image is detected and option "move to next" is enabled, the switcher freezes ComfyUI, likely creating an infinite loop without actually stopping the workflow as it should, with an error. 

Would it be possible to modify it so that when it freezes, it returns an error message instead of entering an infinite loop? 
This issue forces a restart of ComfyUI every time

**Comment by 4lt3r3go** [comment]
one of the cases ![image](https://github.com/user-attachments/assets/86673867-7f9a-4acb-9fab-daac203da2e7)

**Comment by alt-key-project** [comment]
I am glad you found the node useful. Thank you for reporting the issue, this should be an easy fix! I agree - there should be an error in the case when there is no valid input.

**Comment by alt-key-project** [comment]
Pushed a fix for this. Please, do let me know if this resolves your issue!

**Comment by 4lt3r3go** [comment]
WOAH man, that was super fast! 
Amazing!

**Comment by 4lt3r3go** [comment]
a added you in credits of my workflow. thanks again

**Comment by alt-key-project** [comment]
Ok, sometimes I am a bit too fast (I admit I skipped on the testing here). I will revert and see if there is a solution for this.

**Comment by alt-key-project** [comment]
I think(tm) this will solve it. Please, do check if this resolves the issue without the error message.

**Comment by 4lt3r3go** [comment]
I am truly shocked because, while I was trying to figure out if the problem was on my end (maybe I had messed something up while trying to tame this monster of a workflow) you had already made some changes. 
You're incredible! Thank you.

Now everything seems to be working fine.

![image](https://github.com/user-attachments/assets/a9bd779f-6e9c-4d28-8d1b-22765138d7d3)

**Comment by alt-key-project** [comment]
Great - thanks for helping me resolve this issue (in all of the switch nodes.)!
