### ISSUE TITLE
No module named 'evalidate'

### ISSUE THREAD

**Issue by linnkoln** [alt-key-project/comfyui-dream-project#5]
Cannot import E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-project module for custom nodes: No module named 'evalidate'
![image](https://github.com/alt-key-project/comfyui-dream-project/assets/60001135/f6ad2f07-9716-4679-af33-381ee36aa320)

**Comment by alt-key-project** [comment]
Whenever a new module is added to the requirements of any custom node pack, it will cause this problem for people updating with "git pull" - as far as I know (please correct me if I am wrong here) there is no way to support this automatically in comfyui and the manager. You have two options, either simply uninstall and install using the comfyui manager, or run pip install on the requirements file correctly using the python interpreter of your installation (as mentioned in the installation instructions).
