### ISSUE TITLE
Error when trying to add Big Float Switch

### ISSUE THREAD

**Issue by edward-cates** [alt-key-project/comfyui-dream-project#9]
<img width="548" alt="image" src="https://github.com/alt-key-project/comfyui-dream-project/assets/22799309/1e85f6cc-f0a7-4d2f-9143-dc986ff180f7">

**Comment by alt-key-project** [comment]
Thanks for the report! I think the issue is resolved in latest version. However, optional inputs may be tricky in ComfyUI so there could still be some issue here. Do let me know if it works for you now.

**Comment by edward-cates** [comment]
Fixed! Thank you.
